.\" Manpage for hello
.\" Contact vivek@nixcraft.net.in to correct errors or typos.
.TH man 1 "2018/07/29" "1.0" "hello man page"
.SH NAME
hello prints "hello world"
.SH SYNOPSIS
hello
.SH DESCRIPTION
hello is a simple program printing hello world
.SH OPTIONS
hello does not take any options
.SH SEE ALSO
printf(3) 
.SH BUGS
No known bugs.
.SH AUTHOR
Antonino Castelfranco (acastelfranco@gmail.com)
